version: "3"

services:
  consumer-kyc:
    build:
      context: .
      dockerfile: docker/Dockerfile-loc
    container_name: consumer-kyc
    volumes:
      - ./:/go/src/fauzanlucky/consumer-kyc

    command: ["air", "-c", "watcher.conf"]
