FROM golang@sha256:e484434a085a28801e81089cc8bcec65bc990dd25a070e3dd6e04b19ceafaced AS builder

RUN apk update && \
    apk add --no-cache git ca-certificates tzdata bash && \
    update-ca-certificates

RUN go get -u github.com/cosmtrek/air

WORKDIR $GOPATH/src/forkyid/go-consumer-boilerplate
COPY . .

RUN go mod download && go mod verify

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
    -ldflags='-w -s -extldflags "-static"' -a \
    -o /go/bin/main ./src

ENTRYPOINT ["/go/bin/main"]