FROM golang@sha256:e484434a085a28801e81089cc8bcec65bc990dd25a070e3dd6e04b19ceafaced AS builder

RUN apk update && \
    apk add --no-cache git ca-certificates tzdata bash && \
    update-ca-certificates

WORKDIR $GOPATH/src/github.com/forkyid/consumer-kyc-update/src
COPY . .

RUN mkdir docs
RUN go mod download && go mod verify
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
    -ldflags='-w -s -extldflags "-static"' -a \
    -o /go/bin/main ./src

FROM scratch

COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /go/src/github.com/forkyid/consumer-kyc-update/src/.env .env
COPY --from=builder /go/bin/main /go/bin/main

ENTRYPOINT ["/go/bin/main"]